package ruby.bamboo.api;

import net.minecraft.block.Block;
import net.minecraft.block.BlockBush;
import net.minecraft.block.BlockLeaves;
import net.minecraft.block.BlockLog;
import net.minecraft.block.BlockSapling;

public class BambooBlocks {
    public static final BlockBush BAMBOO = (BlockBush) Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "bamboo");
    public static final BlockBush BAMBOOSHOOT = (BlockBush) Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "bambooshoot");
    public static final BlockLeaves BROAD_LEAVE = (BlockLeaves) Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "broad_leave");
    public static final Block JPCHEST = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "jpchest");
    public static final Block KITUNEBI = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "kitunebi");
    public static final Block RICEPLANT = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "riceplant");
    public static final BlockLeaves SAKURA_LEAVE = (BlockLeaves) Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "sakura_leave");
    public static final BlockLog SAKURA_LOG = (BlockLog) Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "sakura_log");
    public static final Block SAKURA_PLANKS = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "sakura_planks");
    public static final BlockSapling SAKURA_SAPLING = (BlockSapling) Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "sakura_sapling");
    public static final Block TATAMI = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "tatami");
    public static final Block BAMBOO_PANE = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "bamboopane");
    public static final Block SPRING_BLOCK = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "spring_block");
    public static final Block SPRING_WATER = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "spring_water");
    public static final Block CAMPFIRE = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "campfire");
    public static final Block ANDON = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "andon");
    public static final Block HUTON = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "huton");
    public static final Block INDLIGHT_WHITE = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "indlight_white");
    public static final Block INDLIGHT_ORANGE = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "indlight_orange");
    public static final Block INDLIGHT_MAGENTA = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "indlight_magenta");
    public static final Block INDLIGHT_LIGHT_BLUE = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "indlight_light_blue");
    public static final Block INDLIGHT_YELLOW = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "indlight_yellow");
    public static final Block INDLIGHT_LIME = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "indlight_lime");
    public static final Block INDLIGHT_PINK = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "indlight_pink");
    public static final Block INDLIGHT_GRAY = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "indlight_gray");
    public static final Block INDLIGHT_SILVER = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "indlight_silver");
    public static final Block INDLIGHT_CYAN = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "indlight_cyan");
    public static final Block INDLIGHT_PURPLE = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "indlight_purple");
    public static final Block INDLIGHT_BLUE = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "indlight_blue");
    public static final Block INDLIGHT_BROWN = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "indlight_brown");
    public static final Block INDLIGHT_GREEN = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "indlight_green");
    public static final Block INDLIGHT_RED = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "indlight_red");
    public static final Block INDLIGHT_BLACK = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "indlight_black");
    public static final Block MILLSTONE = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "millstone");

    // デコレーション系
    public static final Block KAWARA = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "kawara");
    public static final Block KAWARA_DOUBLE_SLAB = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "kawara_double_slab");
    public static final Block KAWARA_SLAB = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "kawara_slab");
    public static final Block KAWARA_STAIRS = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "kawara_stairs");
    public static final Block PLASTER = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "plaster");
    public static final Block PLASTER_DOUBLE_SLAB = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "plaster_double_slab");
    public static final Block PLASTER_SLAB = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "plaster_slab");
    public static final Block PLASTER_STAIRS = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "plaster_stairs");
    public static final Block NAMAKO = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "namako");
    public static final Block NAMAKO_DOUBLE_SLAB = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "namako_double_slab");
    public static final Block NAMAKO_SLAB = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "namako_slab");
    public static final Block NAMAKO_STAIRS = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "namako_stairs");
    public static final Block WARA = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "wara");
    public static final Block WARA_DOUBLE_SLAB = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "wara_double_slab");
    public static final Block WARA_SLAB = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "wara_slab");
    public static final Block WARA_STAIRS = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "wara_stairs");
    public static final Block KAYA = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "kaya");
    public static final Block KAYA_DOUBLE_SLAB = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "kaya_double_slab");
    public static final Block KAYA_SLAB = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "kaya_slab");
    public static final Block KAYA_STAIRS = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "kaya_stairs");
    public static final Block CBIRCH = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "cbirch");
    public static final Block CBIRCH_DOUBLE_SLAB = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "cbirch_double_slab");
    public static final Block CBIRCH_SLAB = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "cbirch_slab");
    public static final Block CBIRCH_STAIRS = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "cbirch_stairs");
    public static final Block COAK = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "coak");
    public static final Block COAK_DOUBLE_SLAB = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "coak_double_slab");
    public static final Block COAK_SLAB = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "coak_slab");
    public static final Block COAK_STAIRS = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "coak_stairs");
    public static final Block CPINE = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "cpine");
    public static final Block CPINE_DOUBLE_SLAB = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "cpine_double_slab");
    public static final Block CPINE_SLAB = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "cpine_slab");
    public static final Block CPINE_STAIRS = Block.getBlockFromName(Constants.RESOURCED_DOMAIN + "cpine_stairs");
}
